socialnetwork/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views



app_name = 'account'

urlpatterns = [
    path('signup/' , views.SignUp.as_view() , name = 'signup'),
    path('logout/' , auth_views.LogoutView.as_view() , name = 'logout'),
    path('login/' , auth_views.LoginView.as_view(template_name = 'account/login.html') , name = 'login'),
    path('suggestion/' , views.Suggestion.as_view() , name = 'suggestion'),
    path('profile/<slug:slugg>/' , views.profile , name = 'profile'),
    path('profile/<slug:slugg>/edit/' , views.profile_edit , name = 'profile_edit'),
    path('profile/<slug:slugg>/follow/' , views.add_follower , name = 'add_follower'),
    path('search/' , views.search_user , name = 'search_user'),
]

socialnetwork/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('new/' , views.PostCreateView.as_view() , name = 'post_create'),
    path('<int:pk>/detail/' , views.PostDetailView.as_view() , name = 'post_detail'),
    path('<int:pk>/delete/' , views.PostDeleteView.as_view() , name = 'post_delete'),
    path('<int:pk>/update/' , views.PostUpdateView.as_view() , name = 'post_update'),
    path('<int:pk>/comment/new/' , views.add_comment_to_post , name = 'comment_create'),
    path('comment/<int:pk>/remove/', views.CommentDeleteView.as_view(), name='comment_remove'),
    path('comment/<int:pk>/reply/' , views.reply_comment , name = 'reply_comment'),
    path('<int:pk>/liked' , views.add_like_to_post_detail , name = 'liked_detail'),
    path('<int:pk>/liked_by' , views.LikeListView.as_view() , name = 'liked_by')
]

socialnetwork/socialnetwork/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , views.home , name="home"),
    path('account/' , include('account.urls' , namespace = 'account')),
    path('account/' , include('django.contrib.auth.urls')),
    path('posts/' , include('post.urls' , namespace = 'post')),
    path('posts/' , include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

socialnetwork/post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User , related_name = 'post' , on_delete = models.CASCADE)
    title = models.CharField(max_length = 256)
    post_picture = models.ImageField(upload_to = 'pictures/%Y/%m/%D/' ,null = True,blank = True, width_field = "width_field" , height_field = "height_field", max_length = 256)
    width_field = models.IntegerField(default = 0)
    height_field = models.IntegerField(default = 0)
    caption = models.TextField(max_length = 256)
    like = models.ManyToManyField(User , related_name = 'likes')
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post:post_detail' , kwargs = {'pk': self.pk} )

    def total_likes(self):
        return self.like.count()

class Comment(models.Model):
    post = models.ForeignKey(Post , null = True, related_name = 'comments' , on_delete = models.CASCADE)
    parent = models.ForeignKey('self' , null = True , related_name = 'replies' , on_delete = models.CASCADE)
    userr = models.ForeignKey(User , null = True , related_name = 'comments' , on_delete = models.CASCADE)
    comment_text = models.TextField(max_length = 256)
    commented_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment_text

    def get_absolute_url(self):
        post = self.post
        return reverse('home')

socialnetwork/post/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = {'comment_text'}

socialnetwork/post/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.views.generic import ListView , DetailView , UpdateView , DeleteView , CreateView , TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post , Comment
from django.urls import reverse_lazy , reverse
from .forms import CommentForm
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
import urllib
# Create your views here.
################################################################################
#post views
liked = False

def home(request , liked = liked):
    users = User.objects.all()
    context = {
        'home_posts': Post.objects.all().order_by('-created_date'),
        'liked':liked,
        'users':users,
    }
    return render(request , 'home.html' , context)

class PostCreateView(LoginRequiredMixin , CreateView):
    model = Post
    fields = {'title' , 'post_picture' , 'caption'}

    def form_valid(self , form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostList(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'profile.html'
    ordering = ['-created_date']


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self , *args , **kwargs):
        post = get_object_or_404(Post , id = self.kwargs['pk'])
        liked = False
        if post.like.filter(id = self.request.user.id).exists():
            liked = True
        else:
            liked = False
        context = super(PostDetailView , self).get_context_data()
        context['total_likes'] = post.total_likes()
        context['liked'] = liked
        return context

class PostUpdateView(UpdateView):
    model = Post
    fields = {'title' , 'caption'}

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('home')

################################################################################
#comment views
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        form.instance.userr = request.user
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'post/comment_form.html', {'form': form})


class CommentListView(ListView):
    model = Comment
    context_object_name = 'comments'
    template_name = 'post/post_detail.html'

class CommentDeleteView(DeleteView):
    model = Comment
    def get_success_url(self , **kwargs):
        post = self.post
        return reverse_lazy('home')

def reply_comment(request , pk):
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        form.instance.userr = request.user
        form.instance.parent = comment
        post = comment.post
        if form.is_valid():
            reply_comment = form.save(commit=False)
            reply_comment.post = post
            reply_comment.save()
            return redirect('post:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'post/comment_form.html', {'form': form})


################################################################################
def add_like_to_post_detail(request , pk):
    post = get_object_or_404(Post , id = request.POST.get('like'))
    if post.like.filter(id = request.user.id).exists():
        post.like.remove(request.user)
        liked = False
    else:
        post.like.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('post:post_detail' , kwargs = {'pk':pk}))

class LikeListView(ListView):
    model = Post
    template_name = 'post/like_list.html'
    context_object_name = 'posts'

socialnetwork/post/templates/post/comment_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Delete Comment</h1>
    <h4>Are you sure you want to delete this Comment</h4>
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" name="" value="Delete">
      <a class="btn btn-secondary" href="{% url 'post:post_detail' comment.post.id %}">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

socialnetwork/post/templates/post/comment_form.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Create Comment</h1>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-success" type="submit" name="" value="Post Comment">
    </form>
  </div>
</div>
{% endblock %}

socialnetwork/post/templates/post/like_form.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Like</h1>
    <form method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-danger" type="submit" name="" value="Like">
    </form>
  </div>
</div>
{% endblock %}

socialnetwork/post/templates/post/like_list.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <ul>
      {{posts.like.count}}
    </ul>
  </div>
</div>
{% endblock %}

socialnetwork/post/templates/post/post_confirm_delete.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Delete Post</h1>
    <h4>Are you sure you want to delete this post --> {{post.title}}</h4>
    <form method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" name="" value="Delete">
      <a class="btn btn-secondary" href="{% url 'post:post_detail' post.id %}">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

socialnetwork/post/templates/post/post_detail.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
  <div style="border: 1px solid #E5E5E5; padding: 10px; background-color: #E5E5E5; border-radius: 20px;" class="single_post">
    <div class="row" style="border-bottom: 1px solid #E5E5E5;">
      <div class="col-lg-1">
        <img class="rounded-circle account-img" style="height: 40px; width: 40px; margin-right: 20px;" src="{{post.author.profile.image.url}}" alt="">
      </div>
      <div class="col-lg-5">
        <h3><a href="{% url 'account:profile' post.author.profile.slug %}" style="text-decoration: none; color: black;">{{post.author}}</a></h3>
      </div>
      {% if post.author == user %}
      <div class="col-lg-6" style="padding-left: 350px;">
        <a class="btn btn-primary" href="{% url 'post:post_update' post.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'post:post_delete' post.id %}">Delete</a>
      </div>
      {% endif %}
    </div>
    <div class="row" style="padding: 10px;">
      <div class="col-lg-5">
        <img style="height: 400px; width: 400px; margin-right: 20px;" src="{{post.post_picture.url}}" alt="">
        <div class="date">
          <small class="text-muted">{{post.created_date}}</small>
          <a href="{% url 'post:liked_by' post.id %}"><h4>{{total_likes}} likes</h4></a>
        </div>
      </div>
      <div class="col-lg-7">
        <h2 style="font-size:40px;"class="display-4">{{post.title}}</h2>
        <h3>{{post.caption}}</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-1">
        {% if liked %}
        <form action="{% url 'post:liked_detail' post.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger" value="{{post.id}}" name="like">Unlike</button>
        </form>
        {% else %}
        <form action="{% url 'post:liked_detail' post.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn btn-danger" value="{{post.id}}" name="like">Like</button>
        </form>
        {% endif %}
      </div>
      <div class="col-lg-11">
        <a class="btn btn-secondary" href="{% url 'post:comment_create' post.id %}">Comment</a>
      </div>
    </div>
  </div><br>
  <h2 style="color: gray;">Comments on this post</h2>
  {% if post.comments.all %}
  {% for comment in post.comments.all %}
  <div class="commentss"  style="border: 1px solid #E5E5E5; border-radius: 20px; padding: 10px; background-color: white;">
    <div class="row">
      <div class="col-lg-1">
        <img class="rounded-circle account-img" style="height: 40px; width: 40px;" src="{{comment.userr.profile.image.url}}" alt="">
      </div>
      <div class="col-lg-5">
        <h6><a href="{% url 'account:profile' comment.userr.profile.slug %}" style="text-decoration: none; color: black;">{{comment.userr}}</a></h6>
      </div>
    </div>
    <div class="row">
      <div class="col">
        {% if comment.parent %}
          <h3><a href="{% url 'account:profile' comment.parent.userr %}">@{{comment.parent.userr}}</a> {{comment.comment_text}}</h3>
          <small>{{comment.commented_at}}</small>
        {% else %}
          <h3>{{comment.comment_text}}</h3>
          <small>{{comment.commented_at}}</small>
        {% endif %}
        {% if user != comment.userr %}
        <a style="text-decoration: none;" href="{% url 'post:reply_comment' comment.id %}">Reply to @{{comment.userr}}</a>
        {% endif %}
      </div>
      {% if post.author == user or comment.userr == user %}
      <div class="col" >
        <a  style="margin-left: 400px;" class="btn btn-danger" href="{% url 'post:comment_remove' comment.id %}">Delete</a>
      </div>
      {% endif %}
    </div>
  </div><br>
  {% endfor %}
  {% else %}
  <h4>No comments on this post yet.</h4>
  {% endif %}
</div>
{% endblock %}

socialnetwork/post/templates/post/post_form.html
{% extends 'base.html' %}

{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h1>Create New Post</h1>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-primary" type="submit" name="" value="Post">
    </form>
  </div>
</div>
{% endblock %}