socialnetwork/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views



app_name = 'account'

urlpatterns = [
    path('signup/' , views.SignUp.as_view() , name = 'signup'),
    path('logout/' , auth_views.LogoutView.as_view() , name = 'logout'),
    path('login/' , auth_views.LoginView.as_view(template_name = 'account/login.html') , name = 'login'),
    path('suggestion/' , views.Suggestion.as_view() , name = 'suggestion'),
    path('profile/<slug:slugg>/' , views.profile , name = 'profile'),
    path('profile/<slug:slugg>/edit/' , views.profile_edit , name = 'profile_edit'),
    path('profile/<slug:slugg>/follow/' , views.add_follower , name = 'add_follower'),
    path('search/' , views.search_user , name = 'search_user'),
]

socialnetwork/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('new/' , views.PostCreateView.as_view() , name = 'post_create'),
    path('<int:pk>/detail/' , views.PostDetailView.as_view() , name = 'post_detail'),
    path('<int:pk>/delete/' , views.PostDeleteView.as_view() , name = 'post_delete'),
    path('<int:pk>/update/' , views.PostUpdateView.as_view() , name = 'post_update'),
    path('<int:pk>/comment/new/' , views.add_comment_to_post , name = 'comment_create'),
    path('comment/<int:pk>/remove/', views.CommentDeleteView.as_view(), name='comment_remove'),
    path('comment/<int:pk>/reply/' , views.reply_comment , name = 'reply_comment'),
    path('<int:pk>/liked' , views.add_like_to_post_detail , name = 'liked_detail'),
    path('<int:pk>/liked_by' , views.LikeListView.as_view() , name = 'liked_by')
]

socialnetwork/socialnetwork/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from post import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , views.home , name="home"),
    path('account/' , include('account.urls' , namespace = 'account')),
    path('account/' , include('django.contrib.auth.urls')),
    path('posts/' , include('post.urls' , namespace = 'post')),
    path('posts/' , include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

socialnetwork/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>TheSocialNetwork</title>
    <link href="https://fonts.googleapis.com/css2?family=Archivo+Black&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/account/acc.css' %}">
  </head>
  <body style="background-color: #f2f2f2;">
    {% if user.is_authenticated %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-bottom: 1px solid #E5E5E5;">
        <div class="container">
          <a class="navbar-brand" style="font-family: 'Pacifico', cursive;" href="{% url 'home' %}"><h2>HrithickGram</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="nav navbar-nav navbar-right">
              <li class="nav-item">
                <a class="nav-link navbar-right" href="{% url 'account:profile' user.profile.slug %}">My Profile</a>
              </li>
              <li>
                <a class="nav-link" href="{% url 'account:logout' %}">Logout</a>
              </li>
              <li>
                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
              </li>
            </ul>
          </div>
          <div class="searchbar">
            <form action="{% url 'account:search_user' %}" class="form-inline my-2 my-lg-0" method = "POST" >
              {% csrf_token %}
              <input class="form-control mr-sm-2" name="search_user_name" type="search" placeholder="Search User" aria-label="Search">
              <button type="submit" class="btn btn-danger">Search</button>
            </form>
          </div>
        </div>
      </nav>
        {% else %}
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <a class="navbar-brand" style="font-family: 'Pacifico', cursive;" href="{% url 'home' %}"><h2>HrithickGram</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item ">
              <a class="btn btn-outline-dark" href="{% url 'account:login' %}">Login</a>
            </li>
          </ul>
        </div>

      </nav>
    {% endif %}
    <p></p>

    {% block body_block %}
    {% endblock %}
  </body>
</html>

socialnetwork/templates/home.html
{% extends 'base.html' %}

{% block body_block %}
{% if user.is_authenticated %}
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      {% for post in home_posts %}
        {% if liked %}

        {% else %}
          <div style="border: 1px solid #E5E5E5; padding: 10px; border-radius: 20px; background-color: #E5E5E5;" class="single_post">
            <div class="row">
              <div class="col-lg-1">
                <img class="rounded-circle account-img" style="height: 40px; width: 40px; margin-right: 20px;" src="{{post.author.profile.image.url}}" alt="">
              </div>
              <div class="col-lg-5">
                <h3><a href="{% url 'account:profile' post.author.profile.slug %}" style="text-decoration: none; color: black;">{{post.author}}</a></h3>
              </div>
              {% if post.author == user%}
              <div class="crup" style="padding-left: 150px;">
                <a style="margin-right: 5px;" class="btn btn-primary" href="{% url 'post:post_update' post.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'post:post_delete' post.id %}">Delete</a>
              </div>
              {% endif %}
              <div class="col-lg-6">

              </div>
            </div>
            <div class="row" style="padding: 10px;">
              <div class="col-lg-7">
                <img style="height: 400px; width: 400px; margin-right: 20px;" src="{{post.post_picture.url}}" alt="">
                <small class="text-muted">{{post.created_date}}</small>
                <a href="{% url 'post:liked_by' post.id %}"><h4>{{post.like.count}} likes</h4></a>
                <a href="{% url 'post:post_detail' post.id %}"><h5 style="color: gray; text-decoration: null;">View all {{post.comments.count}} comments</h5></a>
              </div>
              <div class="col-lg-5">
                <h2 style="font-size:40px;"class="display-4">{{post.title}}</h2>
                <h3>{{post.caption}}</h3>
              </div>
            </div>
            <div class="row">
              <div class="col-lg-1">
                {% if liked %}
                <form action="{% url 'post:liked_detail' post.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger" value="{{post.id}}" name="like">Unlike</button>
                </form>
                {% else %}
                <form action="{% url 'post:liked_detail' post.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger" value="{{post.id}}" name="like">Like</button>
                </form>
                {% endif %}
              </div>
              <div class="col-lg-11">
                <a class="btn btn-secondary" href="{% url 'post:comment_create' post.id %}">Comment</a>
              </div>
            </div>
          </div><br>
        {% endif %}
      {% endfor %}
    </div>
    <div class="col-sm-4"  data-spy="affix" data-offset-top="205">
      <div class="side-note" style = 'padding: 10px; border-radius: 20px; background-color: white;'>
        <div class="row">
          <div class="col-lg-3">
            <img class="rounded-circle account-img" style="height: 80px; width: 80px; margin-right: 20px;" src="{{user.profile.image.url}}" alt="">
          </div>
          <div class="col-lg-9">
            <h3><a href="{% url 'account:profile' user.profile.slug %}" class="namee" style="text-decoration: none; color: black;">{{user.username}}</a></h3>
            <h6 style="color: #A5A5A5;">{{user.email}}</h6>
          </div>
        </div>
        <p></p>
        <a class="btn btn-success" href="{% url 'post:post_create' %}">Create New Post</a>
      </div><br>
      <div class="suggestion" style = 'padding: 10px; border-radius: 20px; background-color: white;'>
        <h3 style="color: gray;">Suggestion</h3><br>
        {% for userr in users %}
          {% if userr.is_superuser or userr == user %}
          {% else %}
            {% if user in userr.followers %}

            {% else %}
              <div class="row">
                  <div class="col-lg-3">
                    <img class="rounded-circle account-img" style="height: 40px; width: 40px; margin-right: 20px;" src="{{userr.profile.image.url}}" alt="">
                  </div>
                  <div class="col-lg-9">
                    <h5><a href="{% url 'account:profile' userr.profile.slug %}" class="namee" style="text-decoration: none; color: black;">{{userr.username}}</a></h5>
                  </div>
              </div><br>
            {% endif %}
          {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% else %}
<div class="container">
  <h1 style="font-family: 'Archivo Black', sans-serif; font-size: 100px;">Welcome to TheSocialNetwork!</h1>
  <br>
  <h3 class="display-4" style="font-size: 40px;">What are you still waiting for. Do you have something interesting to share with others? go on hop inside the website.</h3><br>
</div>
{% endif %}
{% endblock %}